spring:
  application:
    name: eureka
  security:
    user:
      name: eureka
      password: eureka

server:
  port: 8761
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
        env:
          show-values: always #shows sanitized senzitive values
        configprops:
          show-values: always #shows sanitized senzitive values

eureka:
  server:
    metrics: 
      enabled: true
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost #: localhost # needed to prevent constant error messages like this with different localhost-1,4,5,.....
                        # ERROR 74177 --- [eureka] [get_localhost-2] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 401; discarding 1 replication tasks
                        # WARN 74177 --- [eureka] [get_localhost-2] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_localhost-2 due to permanent error
#  server:
#    enable-self-preservation: false # prevents evicting instances when their heartbeats are below the treshlod - true by default
                                     # set to false since it might prevent above ERROR and WARN messages - it did not!
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG