spring:
  application:
    name: gateway
  security:
    user:
      name: gateway
      password: gateway
  reactor:
    context-propagation: AUTO
      
server:
  port: 8081
  
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

---

management:
    tracing:
       propagation:
           type: b3
       enabled: true
       sampling:
           probability: 1
    zipkin:
       tracing:
           endpoint: http://localhost:9411/api/v2/spans
    endpoints:
      web:
        exposure:
          include: '*' 
    
# management.endpoints.web.exposure.include: '*'

---
  
eureka:
 client:
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://eureka:eureka@${eureka.instance.hostname}:8761/eureka/
      defaultZone: http://eureka:eureka@localhost:8761/eureka
#      defaultZone: ${eureka_url:http://eureka:eureka@eureka:8761/eureka}
 instance:
#    hostname: eureka
#    hostname: localhost
    prefer-ip-address: true

---

spring:
  cloud:
    gateway:
      routes:
      - id: airport_route
        uri: lb://AIRPORT/
        predicates:
            - Path=/flight/**
      - id: hotel_route
        uri: lb://HOTEL/
        predicates:
            - Path=/booking/**
      - id: travel_agency_route
        uri: lb://TRAVEL-AGENCY/
        predicates:
            - Path=/arrangement/**
            