INSERT INTO hotel (PRICE_PER_NIGHT, CATEGORY, NAME, ROOM_TYPE, SERVICE_TYPE) VALUES (1,'asd','asd','asd','asd')
INSERT INTO hotel (PRICE_PER_NIGHT, CATEGORY, NAME, ROOM_TYPE, SERVICE_TYPE) VALUES (1,'qwe','qwe','qwe','qwe')
INSERT INTO hotel (PRICE_PER_NIGHT, CATEGORY, NAME, ROOM_TYPE, SERVICE_TYPE) VALUES (1,'zxc','zxc','zxc','zxc')
INSERT INTO hotel (PRICE_PER_NIGHT, CATEGORY, NAME, ROOM_TYPE, SERVICE_TYPE) VALUES (1,'cxz','cxz','cxz','cxz')